
//Schema :
import mongoose, {Schema} from  "mongoose"


const UserSchema = new Schema({
    username : {
        type : String,
        required : true
    },
    password : {
        type : String,
        required : true
    }
})

/* Edeges of the Node */
const EdgesSchema = new Schema({
    id : {
        type : String,
        required : true
    },
    source : {
        type : String,
        required : true
    },
    target : {
        type: String,
        required : true
    }
} , {
    _id:false         /* WE D'not want the Edges Should have autoGenerated Id */
}) 


/* Position of the Nodes */
const PositionSchema = new Schema({
    x: {
        type : String,
        required : true
    },
    y : {
        type : String,
        required : true
    }
},{
    _id : false
})

/* its Node data Schema */
const NodedataSchema = new Schema({
    kind : {
        type : String,
        enum : ["ACTION", "TRIGGER"]
    },
    metadata :Schema.Types.Mixed
})

/* Nodes Itself */
const NodesSchema = new Schema({

    id : {
        type: String,
        required :true
    },

    position : PositionSchema,

    credentials : Schema.Types.Mixed,

    type : {
        type : mongoose.Types.ObjectId,
        ref : 'Nodes' /*This is Foreign Key */
    }, 

    data : NodedataSchema
},{
    _id : false
})



/* [1 : Many ]Relation , Every user can have mant workflows  & Every WorkFlow Belong to 1 user*/
const workflowSchema = new Schema({
    userId : {
        type : mongoose.Types.ObjectId,
        required : true,
        ref : 'Users'                   /*This is an Foreign Key : It an Refrence to User table  */
    },
    nodes : [NodesSchema],
    edges : [EdgesSchema]

})
export const UserModel = mongoose.model("Users", UserSchema);