
//Schema :
import mongoose, {Schema} from  "mongoose"


const UserSchema = new Schema({
    username : {
        type : String,
        required : true,
        unique : true
    },
    password : {
        type : String,
        required : true
    }
})

/* Edeges of the Node */
const EdgesSchema = new Schema({
    id : {
        type : String,
        required : true
    },
    source : {
        type : String,
        required : true
    },
    target : {
        type: String,
        required : true
    }
} , {
    _id:false         /* WE D'not want the Edges Should have autoGenerated Id */
}) 


/* Position of the Nodes */
const PositionSchema = new Schema({
    x: {
        type : Number,
        required : true
    },
    y : {
        type : Number,
        required : true
    }
},{
    _id : false
})

/* its Node data Schema */
const NodedataSchema = new Schema({
    kind : {
        type : String,
        enum : ["ACTION", "TRIGGER"]
    },
    metadata :Schema.Types.Mixed
})

/* Nodes Itself */
const WorkflowNodeSchema = new Schema({

    id : {
        type: String,
        required :true
    },

    position : PositionSchema,

    credentials : Schema.Types.Mixed,

    nodeId : {
        type : mongoose.Types.ObjectId,
        ref : 'Nodes' /*This is Foreign Key */
    }, 

    data : NodedataSchema
},{
    _id : false
})



/* [1 : Many ]Relation , Every user can have mant workflows  & Every WorkFlow Belong to 1 user*/
const workflowSchema = new Schema({
    userId : {
        type : mongoose.Types.ObjectId,
        required : true,
        ref : 'Users'                   /*This is an Foreign Key : It an Refrence to User table  */
    },
    nodes : [WorkflowNodeSchema],
    edges : [EdgesSchema]

})


const CredentialsTypeSchema = new Schema({
    title : {
        type : String,
        required : true
    },
    required : {
        type : Boolean,
        required : true
    }
})


const NodesSchema = new Schema({
    title : {
        type : String,
        required : true
    },

    description : {
        type : String
    },
    type : {
        type : String,
        enum : ["ACTION", "TRIGGER"],
        required : true
    },
    credentialsType : [CredentialsTypeSchema] /* Every Node Should Have Multiple Credentials */
})

const ExecutionSchema =  new Schema({
    workflowId : {
        type :mongoose.Types.ObjectId,
        required : true,
        ref : 'Workflows'
    },
    status : {
        type : String,
        enum : ["PENDING","SUCCESS","FAILURE"]
    },
    startTime : {
        type : Date,
        default : Date.now()
    },
    endTime : {
        type : Date
    }
})
export const UserModel = mongoose.model("Users", UserSchema);
export const workflowModel = mongoose.model("Worksflows", workflowSchema);
export const NodesModel = mongoose.model("Nodes", NodesSchema);
export const ExecutionModel = mongoose.model("Execution", ExecutionSchema);